apiVersion: v2
name: app
description: Universal Kubernetes Helm Chart Boilerplate - Deploy any application to Kubernetes with a single values file. Cloud-agnostic, production-ready chart with ConfigMaps, Secrets, HPA, and PersistentVolumes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.1


# Keywords for Helm Hub and search engines
keywords:
  - helm
  - helm-chart
  - kubernetes
  - boilerplate
  - template
  - cloud-native
  - devops
  - microservices
  - configmap
  - secrets
  - hpa
  - autoscaling
  - persistent-volume
  - kubernetes-deployment

# Home page and sources
home: https://github.com/cogitogroupltd/helm-chart-boilerplate
sources:
  - https://github.com/cogitogroupltd/helm-chart-boilerplate

# Maintainers
maintainers:
  - name: Cogito Group Ltd
    url: https://cogitogroup.co.uk