{{- if .Values.secenv }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "generic.fullname" . }}-secenv"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.secenv }}
{{- if not (empty $value) }}
  {{ $name | nindent 2 }}: {{ $value  | b64enc | quote}}
{{- end }}
{{- end }}
{{- end }}
