{{- if and (.Values.secret.enabled) (.Values.secret.files) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
data:
{{- if .Values.secret.files }}
{{- range $key, $value := .Values.secret.files }}
  {{ $key }}: {{ $value | b64enc}}
{{ "" | indent 0 }}
{{- end -}}
{{- end -}}
{{- end -}}