{{- if .Values.services }}
{{- range $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "generic.fullname" $ }}-{{ $value.name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
spec:
  type: {{ $value.type }}
  ports:
    - name: {{ $value.name }}
      port: {{ $value.containerPort }}
      targetPort: {{ $value.targetPort }}
      {{ if and (eq $value.type "NodePort") ($value.nodePort)}}
      nodePort: {{ $value.nodePort }}
      {{ end }}
      protocol: {{ $value.protocol }}
  selector:
    {{- include "generic.selectorLabels" $ | nindent 4 }}
---
{{- end }}
{{- end }}
