name: middlemail
icon: https://always-icecream.com/generated/static-images/miacademy/shared/aki/aki_small.png
apiVersion: v2
description: Transactional Email
type: application

version: 1.1.0
appVersion: 0.5.0

dependencies:
  - name: rabbitmq
    version: "~7.5.0"
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: rabbitmq.provision
  - name: elasticsearch
    version: "~12.3.5"
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: elasticsearch.provision
  - name: redis
    version: "~10.7.2"
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
